name: Publish VS Code Extension
on:
  push:
    branches:
      - main

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need to fetch at least 2 commits to compare changes
      
      - name: Check if version has changed
        id: check_version
        run: |
          # Get the version from the latest commit
          NEW_VERSION=$(git show HEAD:package.json | jq -r .version)
          # Get the version from the previous commit
          OLD_VERSION=$(git show HEAD^:package.json | jq -r .version)
          
          if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
            echo "Version changed from $OLD_VERSION to $NEW_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup Node.js
        if: steps.check_version.outputs.version_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        if: steps.check_version.outputs.version_changed == 'true'
        run: npm ci
        
      - name: Install vsce
        if: steps.check_version.outputs.version_changed == 'true'
        run: npm install -g @vscode/vsce
        
      - name: Package Extension
        if: steps.check_version.outputs.version_changed == 'true'
        run: vsce package
        
      - name: Publish to Visual Studio Marketplace
        if: steps.check_version.outputs.version_changed == 'true'
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
